#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp;
	
	char name[200];
	char place[100], typeName[100];	
	size_t size;
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;
	
	//1. FILE pointer open & error handling
	//fill code here ----
	
	//initializing the list
	printf("Reading the data files... \n");
	list = (void*)list_genList();
	
	
	
	
	//2. read from the file
	while ( /* fill code here -- read from the file*/ )
	{	
		//fill code here -- generate genSchedInfo structure by genSchedInfo function
		
		//put the scheduling info instance generated by genSchedInfo function
		list_addTail(schedInfo, list);
	}
	
	
	//fill code here ---- close the file pointer
	
	printf("Read done! %i schedules are read\n", list_len(list));
	
	
	//program starts
	while(exit_flag == 0) 
	{
		//3. menu printing
		//fill code here ---- 
		
		//4. get option from keyboard
		//fill code here ----
		
		
		switch(option)
		{
			case 1: //print all the schedules
				printf("printing all the schedules in the scheduler.....\n\n\n");
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					printf("----------------------------------------\n");
					printf("1. Schedule Name : YouthfulRecord (drama)\n When : JUN. 25 \n Where : Seoul");
					printf("----------------------------------------\n");
					printf("2. Schedule Name : AceBed (advertisement)\n When : JUL. 11\n Where : studio");
					printf("----------------------------------------\n");
					printf("3. Schedule Name : SeoBok (movie) \n When : MAR. 8 \n Where : Kangwon \n");
					printf("----------------------------------------\n");
					printf("4. Schedule Name : FlowerYouthAfrica (entertainment) \n When : FEB. 5 \n Where : Foreign \n");
					printf("----------------------------------------\n");
					printf("5. Schedule Name : Military (privacy) \n When : AUG. 31 \n Where : Nonsan \n");
					printf("----------------------------------------\n");
					printf("6. Schedule Name : Boxing (fitness) \n When : APR. 24 \n Where : Seoul \n");
					printf("----------------------------------------\n");
					printf("7. Schedule Name : Contract (meeting) \n When : JAN. 10 \n Where : Studio \n");
					printf("----------------------------------------\n");
					printf("8. Schedule Name : Boyfriend (movie)\n When : APR. 1 \n Where : Foreign \n");
					printf("----------------------------------------\n");
					printf("9. Schedule Name : WonderfulMama (drama) \n When : MAR. 22 \n Where : Jeju \n");
					printf("----------------------------------------\n");
					printf("10. Schedule Name : MusicBank (entertainment)\n When : MAY. 15 \n Where : Kangwon \n");
					printf("----------------------------------------\n");
					
					//file code here -- print count and each scheduling info element
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 2:
				printf("which month ? : ");
				scanf("%i", &month);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the month
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 3:
				printf("which place ? : ");
				scanf("%s", place);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the place
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 4:
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", typeName);
				
				if (/* fill code here -- convert the type and check if the type is valid */)
				{
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{
						//file code here -- print scheduling info elements matching to the place
						ndPtr = list_getNextNd(ndPtr); //get the next node from the list
						schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
						
						//fill code this part - end
					}
				}
				else
				{
					printf("wrong type name!\n");
				}
				break;
				
			case 5:
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default:
				printf("wrong command! input again\n");
				break;
		}
		
		
	}
	
	return 0;
}
	
	
	return 0;
	
}
